### ISSUE TITLE
By default NuGet complains about strongly-named assembly

### ISSUE THREAD

**Issue by monty241** [Silvenga/Rocket.Chat.Net#4]
After deploying either 0.2.0.1 or 0.3.01-pre, unit tests raise:
```
Result StackTrace:	
at xxx.Rocketchat.Server.SendMessage(String roomName, String text)
   at xxx.Rocketchat.Server.Send(String roomName, String text)
   at xxx.UnitTest.RocketChatTest.SendMessage() in C:\ws\xxx\RocketChatTest.cs:line 24
Result Message:	
Test method xxx.UnitTest.RocketChatTest.SendMessage threw exception: 
System.IO.FileLoadException: Could not load file or assembly 'Rocket.Chat.Net, Version=0.2.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. 
A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
```
Better would have the NuGet made such that it does not occur.

**Comment by Silvenga** [comment]
Yeah, this is expected - my assemblies are not strongly signed. I won't sign my assemblies without a good reason - why do you need strongly signed versions of my assemblies?

**Comment by monty241** [comment]
We always use them for documented reasons. It makes it harder to get started with the package. I have created an alternative myself; was easier than making it work.

**Comment by Silvenga** [comment]
Yes, self-signing is generally the recommended solution. What do you mean documentation reasons?

**Comment by monty241** [comment]
Sorry, typo, "documented" or known reasons. Work and costs can be painful. But note that error is on strong-naming, not on signing.
